# Generated by Django 4.0.3 on 2023-07-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachado',
            name='asientos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='programado',
            name='estado',
            field=models.CharField(choices=[('0', 'Cancelado'), ('1', 'Programado')], default=1, max_length=2),
        ),
    ]
